spring.application.name=taxi-brousse

# Server port (optional, default is 8080)
server.port=8080

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/taxibroussedb
spring.datasource.username=postgres
spring.datasource.password=snow

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=validate

spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true